### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by JohanAke1** [IgnisDa/ryot#1078]
Does Ryot really respect the telemetry disable variable? As I have that set but I can still see Umami being blocked in my ublock. 

post xhr https://umami.diptesh.me/endpoint

What is the telemetry used for? Why the need to collect data from peoples own servers? Telemetry on self-hosted is intrusive. Having pay-walled features on self-hosted was a bit weird but having telemetry on top of that is already ridiculous.

**Comment by JohanAke1** [comment]
In your clear documentation it is "disable_telemetry:" which is what I use in the config file.

The project is really nice and I thank you for it. It just defeats the whole purpose of self-hosting which for most is to have control of their own data which is I stopped using it.

**Comment by Elite-Alien** [comment]
> In your other comment on an issue, it seems you are not setting the correct env variable. As **clearly** written in https://docs.ryot.io/configuration#important-parameters, the env variable to be set in `DISABLE_TELEMETRY`.
> 
> Moreover, I do not really like the accusatory tone you use. If you feel like the project is violating your privacy/is ridiculous, you are more than welcome to not use it.

I stumbled across "Control your data" like posts on a Reddit I found via web search. Only to see "FRONTEND_UMAMI_SCRIPT_URL" & "FRONTEND_UMAMI_WEBSITE_ID" shoved into the container the documentations that I saw didn't show it. Easy to over look as you don't express it heavily that it's there in the installing parts, Github, or anywhere upfront. It's tucked away in "Configuration" and just learned about with a bloody "DISABLE_TELEMETRY" to learn about it. As this could easily be a add these environment tags to your yaml or at least something posted upfront on the Github page about using telemetry. Since "Configuration" is kind of vague as that is usually used as sort of a software manual of sorts. Which I and I would imagine many do not dive into. You setup a project and seek to learn it on your own a bit to grab hold of it. 

All that said the fact I can disable it did give me some reassurance. Yet, you being asked, "What is the telemetry used for?" not to answer it and go on attack, with your attitude kind of puts a bad taste to Ryot. I was going to buy three lifetime license for my server and set this up for two more of my family members. Yet, now I am not so sure. What do you use it for and you jumping to "Stop accusing me" just doesn't sit right. I think I will be removing Ryot as well. Along with hopefully others that find there way here. The lack of professionalism and just the way you lack any transparency on it has muddied the waters.

Thank you @JohanAke1 for bringing this up and taking the wrath of the creator. Be it his passion put into a neat project that I respect. Though, not the type of approach he should have taken with you. We both should steer ourselves towards MediaTracker instead it seems.

**Comment by IgnisDa** [comment]
I [added](https://github.com/IgnisDa/ryot/commit/d5f1e11c84e69242c79284588cd760c2da9d8f2b) a section to the docs about telemetry. I put it on the first page of the documentation so that people are aware of this from the start.

I understand that this is my fault and i have taken corrective measures to make people aware of the same.

That being said, please get rid of the entitled attitude. I have had people email/discord me racist stuff, an it is disheartening to see.

**Comment by Elite-Alien** [comment]
I appreciate your passion for your project and the fact you did that you made those changes.

As for the other stuff. You can think I have whatever attitude or I am out to get you if you wish. I am sorry if you feel that way, but I came in this topic seeing you not answer @JohanAke1 questions about the telemetry and lash out at him. You could have just answered why it was using it. Instead you ignored it to only lashed out at him for asking. Claiming he has tones in text, when text is very subjective to the reader in a lot of cases, until it goes to name calling. Along with telling him to just stop using your project... When if you just explained why, maybe he would have accepted it and continued to use the project. Along with myself as well.

Not liking your approach makes me question this project towards my own views of what I want running on my machine. It has nothing of malice or anything towards you. Nor did I suggest you take out the telemetry and make any real demands of you. I offered a suggestion on making it clear and that was it. Which I appreciate you did..... Nor am I in said group of e-mail chains or on your Discord. If that said stuff happened that is those people and not us. There is no need to take that anger and project it towards us. Sorry if said stuff happened to you, but again not those people so I will not apologize for something I did not do.

Anyway, have the nicest day you can. I have not and will not have malice towards you or come at you in any shape or form. This will be my last message towards you. Thanks again for making the changes.

**Comment by VikramSeth1** [comment]
Bro.. I 100% agree with @Elite-Alien on this. Very unprofessional. WTF Discord & Emails as if that was to do with this. @IgnisDa 
#LeavingRyot #HelloMediaTracker
