### ISSUE TITLE
Add the option for the admin/first-user to "disable new account registration".

### ISSUE THREAD

**Issue by flavorgold1** [IgnisDa/ryot#173]
I see this feature as a must-have.

Otherwise, leaving this service open on the internet will be difficult.

**Comment by IgnisDa** [comment]
https://github.com/IgnisDa/ryot/blob/27cf8b41ecbf38993bcb2a0413f89f9c73efccfa/libs/generated/src/config/backend/schema.ts#L185

**Comment by flavorgold1** [comment]
> https://github.com/IgnisDa/ryot/blob/27cf8b41ecbf38993bcb2a0413f89f9c73efccfa/libs/generated/src/config/backend/schema.ts#L185

So, how do I access this setting and set it to `false`?

**Comment by IgnisDa** [comment]
Please read the configuration section of the readme.

**Comment by timconsidine** [comment]
This does not appear to work in 2.17.2
Deployed on cosmos

**Comment by IgnisDa** [comment]
@timconsidine Are you sure? its working for me. Can I see your docker-compose (or whatever else you have)?

**Comment by timconsidine** [comment]
Well, I guess I was wrong, because trying to register does have a disabled register button.
But the login screen still shows `Register here` which I think is misleading.
More normal practice is to remove the link to the registration page, rather then have a 'dead' registration page,
Maybe a UI issue.
So yea, sorry, working, but non-standard approach.

**Comment by IgnisDa** [comment]
Yep that makes sense. Will fix that.
