### ISSUE TITLE
Unknown column 'collection.description' in 'field list error upon updating to 1.11.2

### ISSUE THREAD

**Issue by quamok** [IgnisDa/ryot#186]
I've tried updating to version 1.11.2 and I'm getting this MySql error. Is there any command that needs to be ran upon updating? I'm running Ryot in a docker container.

> 07/14/2023 9:15:54 AM
2023-07-14T13:15:54.450027Z  INFO ryot: Running version 1.11.2
07/14/2023 9:15:54 AM
2023-07-14T13:15:54.595250Z  INFO ryot: Using database backend: "MySQL"
07/14/2023 9:15:54 AM
2023-07-14T13:15:54.597302Z  INFO sea_orm_migration::migrator: Applying all pending migrations
07/14/2023 9:15:54 AM
2023-07-14T13:15:54.604078Z  INFO sea_orm_migration::migrator: Applying migration 'm20230707_000015_add_description_and_visibility_fields'
07/14/2023 9:15:54 AM
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Query(SqlxError(Database(MySqlDatabaseError { code: Some("42S22"), number: 1054, message: "Unknown column 'collection.description' in 'field list'" })))', apps/backend/src/main.rs:158:35
07/14/2023 9:15:54 AM
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Container stopped

**Comment by IgnisDa** [comment]
What version did you have before?

**Comment by quamok** [comment]
I don't have exact logs, but my best guess by looking at initial setup date would be 1.5.2

**Comment by IgnisDa** [comment]
Would it be possible for you to send me a dump of your database so that I could examine what went wrong?

**Comment by quamok** [comment]
[CA_backup_mysql-ryot.tar.gz](https://github.com/IgnisDa/ryot/files/12051506/CA_backup_mysql-ryot.tar.gz)

Here it is!

**Comment by IgnisDa** [comment]
Can you send me the docker compose file and password of the root user?

**Comment by quamok** [comment]
Here's the Docker run command

> docker run
  -d
  --name='ryot'
  --net='bridge'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="soltis"
  -e HOST_CONTAINERNAME="ryot"
  -e 'WEB_INSECURE_COOKIE'='true'
  -e 'DATABASE_URL'='mysql://ryot_user:REDACTED@192.168.20.7:3306/ryot_db'
  -e 'VIDEO_GAMES_TWITCH_CLIENT_ID'='REDACTED'
  -e 'VIDEO_GAMES_TWITCH_CLIENT_SECRET'='REDACTED'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8000]/'
  -p '8002:8000/tcp'
  -v '/mnt/user/appdata/ryot':'/data':'rw' 'ghcr.io/ignisda/ryot:latest'

The MariaDB root password will be sent privately.

**Comment by IgnisDa** [comment]
Thanks will look into it.

**Comment by IgnisDa** [comment]
Hi I am not able to find the problem. The error does come up for me, but I don't know how to fix it 😅. I have no experience with MariaDB (is that equivalent to MySQL?). What you can do to fix it:

- Perform a data only dump for MySQL (for Postgres, you'd do this using `docker exec -it -u postgres postgres-ryot pg_dump --column-inserts --data-only ryot > /tmp/file.sql`).
- Reset the database.
- Start up Ryot and let migrations run.
- Import all previous data by running the exported file above against your DB

If possible, I would strongly suggest you to move to Postgres since that is the only DB I actively test against.

Again, really sorry for not being able to help.
