### ISSUE TITLE
[FEATURE REQUEST] Clear searchbox when switching between media categories

### ISSUE THREAD

**Issue by bretthysuik** [IgnisDa/ryot#333]
An example scenario to reproduce:

1. Navigate to "Video Game" media list
2. Click "Search" tab
3. Type in "Pikmin 4" in the search bar. Observe correct result is found
4. Navigate to "Movie" media list
5. Click "My Movies" tab. Observe nothing is displayed because the searchbox still has "Pikmin 4" entered

This always trips me up after searching for something and then switching to another media category and seeing no results. The searchbox should be cleared when switching between media categories.

**Comment by IgnisDa** [comment]
Should be easy enough to do.

**Comment by IgnisDa** [comment]
@bretthysuik I will not be implementing this since removing the functionality breaks the browsing experience. If you look for a movie of the search tab and then check out the details and then come back to the movie search page, the query is gone (with this issue). I don't really like it.

I do admit changing the media type and the search persisting is a little jarring but there's no straightforward way of solving this since the frontend is a pre-rendered app and state management becomes difficult. 

If you have a way to fix this problem without breaking the browsing experience, feel free to create a PR.
