### ISSUE TITLE
[FEATURE REQUEST] - Exercises template/schedules

### ISSUE THREAD

**Issue by edersong** [IgnisDa/ryot#461]
Add a way to prepare all the execises previously to be performed at the gym and set the dates that I'm intend to perform the same set of exercises, so grouping exercises like a "template" and set dates in advance to perform it like a "schedule".

**Comment by IgnisDa** [comment]
There's no concept of templates now. I personally don't use them, since I just tend to repeat older workouts.

That being said, I will implement this feature, but not in the foreseeable future.

**Comment by edersong** [comment]
Collections shouldn't be used for it?

**Comment by IgnisDa** [comment]
You could definitely use them until a better solution is implemented. I want to add additional features like planning and reminders (open to suggestion).

**Comment by edersong** [comment]
Collection will be enough, but there isn't an option to all exercices from collection directly to a Workout in progress or to start a Workout based on a collection.
Additionally, Planning and reminders can be set (in a future) based on collections.
For now, it will be good to start a Workout based on a collection or/and add exercises to a Workout in progress.

**Comment by IgnisDa** [comment]
> For now, it will be good to start a Workout based on a collection or/and add a collection to a Workout in progress.

Yeah that's what I plan to do with templates and schedules.

**Comment by IgnisDa** [comment]
@civilblur I'm not really sure what you mean. can you give an example?

**Comment by IgnisDa** [comment]
I feel like you might not have seen the "Repeat" button on the workout's details page. If you repeat a workout, the same workout is duplicated. Will that fulfill your requirements?

**Comment by IgnisDa** [comment]
I agree. The repeat button doesn't really work if you need to pre-plan your workout. I'll look into implementing templates soon.

**Comment by amedcalf** [comment]
This is a great app already! I would also like to see exercise template style feature.

For me, in the short term I would get a lot of what I want if when adding an exercise to  the workout I could filter to show only exercises from a certain collection, in the same way as you can already filter on muscle, type etc.

I also repeat a lot of exercises each time so it's great that your last sets are shown (weight and reps) - a tiny addition I'd request that could help until templates are developed might be a button that automatically sets the weight and reps of your current exercise to the same as you did last time. It's easy enough to type it in as the app already shows it in the workout page, but a button would save a tiny amount of effort.

Thanks for the consideration and a great tracker app!

**Comment by IgnisDa** [comment]
> For me, in the short term I would get a lot of what I want if when adding an exercise to the workout I could filter to show only exercises from a certain collection,

This is a great idea, could you please create a new issue for this?

>  It's easy enough to type it in as the app already shows it in the workout page, but a button would save a tiny amount of effort.

Thanks for the suggestion, but I think I won't add this since it would clutter the UI. But I plan to get to implementing templates soon enough so it wont be a problem for long.

When you say templates, what exactly do you mean by them? I have a certain feature expectation in mind but I would love to know what others expect so that I can improve on it.

**Comment by amedcalf** [comment]
> > For me, in the short term I would get a lot of what I want if when adding an exercise to the workout I could filter to show only exercises from a certain collection,
> 
> This is a great idea, could you please create a new issue for this?

Thank you! I have created an issue [here](https://github.com/IgnisDa/ryot/issues/605).

> > It's easy enough to type it in as the app already shows it in the workout page, but a button would save a tiny amount of effort.
> 
> Thanks for the suggestion, but I think I won't add this since it would clutter the UI. But I plan to get to implementing templates soon enough so it wont be a problem for long.
> 
> When you say templates, what exactly do you mean by them? I have a certain feature expectation in mind but I would love to know what others expect so that I can improve on it.

Understood, I am sure you have a great vision for keeping the UI simple!

Regarding templates, what would work best for me is if I can create templates that include the exercises my personal trainer has recommended. They would include certain exercises, and the number of reps, sets and weights that I am supposed to do. For instance it might say 3 sets of 20 pushups. 

I could then start a workout that already had that information filled in that I could then confirm whether I did it or not.That would help me make sure I am always remembering to do the exercises, weights, sets and reps that my trainer suggested.

For me the number of exercises is quite large so in a single session I would not complete all of them, so a "copy previous workout" is not quite the same (although I suppose I could create a "fake" workout that included all the exercises I am interested in and delete the ones I'm not going to do in a session).

I could also imagine someone pre-planning a set of exercises, reps, weights and sets in order to e.g. focus on a particular muscle or for a certain gym's machines.

**Comment by IgnisDa** [comment]
Thanks for the explanation. I will take this into account when implementing templates.

**Comment by IgnisDa** [comment]
>  a tiny addition I'd request that could help until templates are developed might be a button that automatically sets the weight and reps of your current exercise to the same as you did last time.

@amedcalf I'm not sure if you have discovered this, but I added this feature a while ago :)

**Comment by IgnisDa** [comment]
Also to anyone following this issue, this issue will require a fair amount of development effort, so I have decided to make it a part of Ryot Pro.

**Comment by amedcalf** [comment]
Thanks @IgnisDa ! I had indeed noticed the change and already use it a lot :) 
And best of luck with Ryot Pro, I'm sure the overall feature is quite complicated to make.

**Comment by IgnisDa** [comment]
This has been released a pro feature. You can demo it using the link in the readme.
