### ISSUE TITLE
[FEATURE REQUEST] - Recommendations

### ISSUE THREAD

**Issue by ghost** [IgnisDa/ryot#53]
Implement a recommendation system based on users' tracked activities. For example, if a user enjoys a particular genre of books, Ryot can suggest similar books or authors they might like.

**Comment by IgnisDa** [comment]
I do not want Ryot to be a recommendation system, only a tracking system. That being said maybe we can have integration with third party APIs that can handle recommendation.

**Comment by JediMaster25** [comment]
You are right, this is better left to an API otherwise it would require a lot of data that could only be gathered by someone who made a public website using this program, and it would require user permissions, and the algorithm to find similarities would be very complex. If I encounter an API that recommends media I'll be sure to write it down here.

**Comment by IgnisDa** [comment]
Thanks for your suggestions! Closing.

**Comment by IgnisDa** [comment]
I now plan to add a new recommendations section on the dashboard.

Notes to self:
- Seed the recommendations using the current date

**Comment by IgnisDa** [comment]
Released as part of [Ryot Pro](https://ryot.io).
