### ISSUE TITLE
Upgrade on bare-metal installation (with no precompiled v3.5.4 binary)?

### ISSUE THREAD

**Issue by lo48576** [IgnisDa/ryot#535]
I'm running baremetal installation of ryot v3.4.0 (on [TurnKey Linux PostgreSQL](https://www.turnkeylinux.org/postgresql) v17.1 (LXC container) on [Proxmox VE](https://pve.proxmox.com/wiki/Main_Page)) and I'm going to upgrade this instance to v4.0.0. 

[Migration docs](https://ignisda.github.io/ryot/migration.html#from-v3-to-v4) says:

> 1. Upgrade the server to v3.5.4 to make sure all pending migrations are applied. For example, you can make this change: image: "ghcr.io/ignisda/ryot:v3.5.4" in your docker-compose file.

However, latest precompiled binary on GitHub releases before v4.0.0 is v3.4.0 (not even 3.5.0) so I cannot proceed this step (without compiling v3.5.4 locally).
So, my question is:

* Is precompiled binary installation still supported as first-class citizen?
* Is it safe to upgrade from v3.4.0 to v4.0.0 in one step?
    * If not, should I build v3.5.4 locally to migrate?
* Is there any reasons to only release limited versions of precompiled binaries (mainly vX.Y.0)?
    * Any plan on more frequent releases on GitHub releases?

**Comment by IgnisDa** [comment]
> Is precompiled binary installation still supported as first-class citizen?

No, I can provide some help with it but I removed it since the server now has 4 running components: `supervisord`, `caddy`, `backend` and `frontend`

> Is it safe to upgrade from v3.4.0 to v4.0.0 in one step? 

No, there are some migrations in v3.5.4 which are necessary.

> Is there any reasons to only release limited versions of precompiled binaries (mainly vX.Y.0)?

I normally just delete the releases that are generated by patch upgrades and put the release notes in the older release. For example, if I release `v3.4.5`, I will delete the release created by github actions and put the release notes in `v3.4.0`.

Sorry for removing the precompiled binary installation method, but it is simply too complicated to include as a viable method. 

I am open to suggestions on what I can do to help you.

**Comment by lo48576** [comment]
Thank you for quick response!
My instance is very young (one week or so) and has very few data stored, so I'll try another installation method (including docker compose).

**Comment by IgnisDa** [comment]
Yep you can export the data from the Your Data page and then import it as generic json.
