### ISSUE TITLE
[FEATURE REQUEST] - Import from jellyfin

### ISSUE THREAD

**Issue by IgnisDa** [IgnisDa/ryot#563]
### Discussed in https://github.com/IgnisDa/ryot/discussions/562

<div type='discussions-op-text'>

<sup>Originally posted by **zombiehoffa** January  9, 2024</sup>
I have a lot of stuff already watched, I dont' see an obvious way to do a one time import. Any suggestions?</div>

**Comment by IgnisDa** [comment]
@zombiehoffa I'll create importers for these since they're much requested features.

**Comment by zombiehoffa** [comment]
You sir, are a golden God! Any chance of kavita integration, airsonic integration,  and dim integration? That completely fills out my potential media consuming softwares.

**Comment by IgnisDa** [comment]
I don't have these software setup, so won't be implementing them anytime soon. But I'll see what I can do.

**Comment by IgnisDa** [comment]
@zombiehoffa Do you plan to import podcasts from ABS or just audiobooks?

**Comment by IgnisDa** [comment]
@zombiehoffa I released ABS support in `v4.1.3`.

**Comment by IgnisDa** [comment]
@zombiehoffa Are you aware of any open source application that uses Jellyfin API Keys. Most endpoints are not working and documentation for the Jellyfin API is non-existent.

**Comment by zombiehoffa** [comment]
No i am not unfortunately. I am honestly not that impressed with that project. It feels like the legacy poor quality code from forking emby has overwhelmed them and they aren't able to maintain what they have let alone improve it. I am still using it and likely will for some time but i am also watching progress on dim and if/when that hits my minimum feature set i will be off jellyfin. In the mean time, it's a best of a bad situation app for me (which makes me sad because they don't need that much to be great for my use case. Support direct play from alternate sources [which is already built into the server from emby days!], remember my filter/sort settings [it's been 5+ years guys, you seriously haven't fixed this obvious problem by now???], keep ffmpeg/vdpau et al updated more quickly in the docker container so newer gpus work for transcoding more quickly, respect my mpv optimizations if I have followed your documentation and put an mpv.conf file in the right spot).

**Comment by IgnisDa** [comment]
Haha, I understand your frustration. Fortunately, I don't use Jellyfin/Plex etc. I just download movies/shows onto my tablet and watch it from there.

As for Dim, I made an issue long ago but there was no response. Maybe you can chime in there? https://github.com/Dusk-Labs/dim/issues/562.

**Comment by IgnisDa** [comment]
@zombiehoffa Finally found a solution and working on this. Would it be possible for you to give me access to your media server? I do have a Jellyfin instance but it does not have much data and I would like to account for all edge cases.
