### ISSUE TITLE
[Feature Request] Add ability to skip seasons/specials

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [IgnisDa/ryot#58]
Quite a few times, tv shows have a separate "season" for Specials, which most users do not watch - add the ability to skip these or any other episode/season.

**Comment by IgnisDa** [comment]
WDYM by skip these seasons? You can just ignore these seasons when looking at the seasons tab.

**Comment by IgnisDa** [comment]
Shows and podcasts are a bit complicated to calculate. So for now, they are not automatically removed from "In Progress".

**Comment by LnLcFlx** [comment]
Specials are usualle bundled in a "Season 0" while the normal seasons start at 1. One could simply add an option to "skip" season 0 so watched shows don't end up in "In Progress".

**Comment by IgnisDa** [comment]
> One could simply add an option to "skip" season 0 so watched shows don't end up in "In Progress".

Where would one have this skip option? As a preference in the settings so that the season does not show up in the seasons tab?

BTW concerning https://github.com/IgnisDa/ryot/issues/58#issuecomment-1563966979, this is no longer true.

**Comment by LnLcFlx** [comment]
> Where would one have this skip option? As a preference in the settings so that the season does not show up in the seasons tab?

For example. That would be great!

> BTW concerning [#58 (comment)](https://github.com/IgnisDa/ryot/issues/58#issuecomment-1563966979), this is no longer true.

Great. I actually just had some difficulties removing certain shows from "In Progress" because they kept popping up again.
Might be my mistake, but it does feel a little unintuitive.
I think I fixed it now using "Mark as dropped".
But it's still weird that removing the "In Progress" tag does nothing.
And I was also wondering what "Stop monitoring" does exactly...

Btw great project, and thanks for the work!

**Comment by IgnisDa** [comment]
>  because they kept popping up again.

This is actually a bug that will be fixed in #355.
