### ISSUE TITLE
Anilist media relation?

### ISSUE THREAD

**Issue by toprak** [IgnisDa/ryot#594]
It does not show any prequel sequel etc. I think it should be there too also what does monitoring do.

**Comment by IgnisDa** [comment]
Adding support for prequels/sequels is not something I want to do since I don't use that feature. If you really need to see them, click on the link in the image that will directly guide you to the anilist webpage where you can see complete anime details.

You can use monitoring for media items that you want updates for. For eg: a new episode was released, status was changed, release date was postponed etc. It mostly applies to movies and shows (via TMDb).
