### ISSUE TITLE
Can I skip an episode or season of a show?

### ISSUE THREAD

**Issue by darthlite** [IgnisDa/ryot#666]
I’m playing around with the demo and this seems like a great project!

I would love it if it was possible to skip certain episodes or seasons of a show. By ‘skip’ I mean not mark them as watched, not have them contribute to my ‘watched’ statistics, but still count as completed if we’re talking about the % of episodes watched.

I would do this for anthology shows, for example, or even interview podcasts where the topic/guest does not interest me.

Does this kind of thing already exist? If so, I couldn’t find it in the demo. If not, is it something that can be added?

Thanks!

**Comment by IgnisDa** [comment]
> Does this kind of thing already exist? If so, I couldn’t find it in the demo. If not, is it something that can be added?

It doesn't exist. And I don't think it's needed at all. If you want to skip something, just don't mark it as seen.

Adding something like this will make summary calculation much more complicated (it already is).

**Comment by darthlite** [comment]
After playing around with the demo some more, I think that makes sense. I came into this with more of a Trakt mindset, but it seems the workflow of Ryot is a little different. In Trakt, any unseen episodes will still be shown in the "Up Next" section and that bothered me, so I would have to mark them as seen and accepted that that will mess up my stats. In the Ryot demo, I think the next episode that shows up when "update progress" is selected is always going to be the one after the latest watched episode based on what I've seen? If so, that is good enough for me.

Some follow-up questions:

1. Is there somewhere I can learn more about the workflow of Ryot? For example, I was a little confused about the difference between "monitored" and "in progress". I think that "in progress" refers to the user's progress not the show's progress, and that "monitored" is about the "Upcoming" and "calendar" sections; is that right?
2. Also, functionally, what do the two options "Dropped" and "On Hold" do? I put a show on hold to test this out, and got a banner "You are currently watching this (100%)" despite not having watched all the episode. Is this intended behavior? 
4. To mark an episode as seen, I would go into the show and update my progress. Is there a quicker way to do that? I have Trakt's "Up Next" section in mind here where on the "dashboard" I can view a list of where I currently am in each show, and with the tap of a button mark the episode that is up next as seen.

**Comment by IgnisDa** [comment]
> always going to be the one after the latest watched episode based on what I've seen

Yes, this is the case.

>  I think that "in progress" refers to the user's progress not the show's progress

It just means that you are consuming this media. Internally, the media is just added to the "In Progress" collection, so you can remove it from your "In Progress" anytime.

>  "monitored" is about the "Upcoming" and "calendar" sections

No. Monitoring a media means that you will get updates related to that media/person in your configured notification providers. Here is an example of notification sent:

![image](https://github.com/IgnisDa/ryot/assets/60938164/2d45af5f-7086-41d7-a0ea-75b55234e64f)

> Also, functionally, what do the two options "Dropped" and "On Hold" do?

Marking a media as "dropped" or "on hold" will remove it from the "In Progress" collection. Marking as "dropped" will invalidate the seen entry currently in progress, so that you can not resume it. "on hold" will just put that seen entry on hold and you can resume it later if you wish.

For example, I watched a few episodes of Lucifer and did not like it. So i mark it as dropped, so that I know never to watch it again.
FOr example, I started playing the game Stray and completed half of it. Then something came up and I couldn't play it for a month. So I marked it on hold. A month later I resumed playing it.

Both "Dropped" and "On Hold" are just indicators to you. Really, it is up to you to decide how you wanna use them. 

> To mark an episode as seen, I would go into the show and update my progress. Is there a quicker way to do that? I have Trakt's "Up Next" section in mind here where on the "dashboard" I can view a list of where I currently am in each show, and with the tap of a button mark the episode that is up next as seen.

I am aware of this, but haven't really been able to think of any good workflow to do this that would also match with Ryot's current flow. It is not a high priority issue for me though.

**Comment by IgnisDa** [comment]
Also you mentioned that you used Trakt. Did you import data from there? I am interested in knowing how people coming from other platforms are able to settle into using Ryot.

**Comment by IgnisDa** [comment]
@darthlite I recommend you wait for https://github.com/IgnisDa/ryot/pull/669 to be merged before importing from Trakt.
