### ISSUE TITLE
Allow searching for media groups

### ISSUE THREAD

**Issue by IgnisDa** [IgnisDa/ryot#695]
- [ ] groups list page should only have those groups who have `user_to_entity` element
- [ ] allow monitoring and adding reminders for groups

**Comment by IgnisDa** [comment]
It remains to be decided when groups are related to users. Should it be when a `user_to_entity` for an entry of a group is created, or should it be done when media group is monitored/reminder created etc?

**Comment by IgnisDa** [comment]
@LnLcFlx what do you think about the above ^?

**Comment by LnLcFlx** [comment]
I'd say both. Since anything else would be unintuitive. You want to see what groups you have watched movies of and when you manually monitor groups then you obviously what to see that too.

I would then add filtering options like in the other tabs.

**Comment by IgnisDa** [comment]
@LnLcFlx but then if i apply the same logic to the people Search then it would end up associating like 100 people for each movie which will defeat the purpose of your original issue (#694).

**Comment by LnLcFlx** [comment]
I think I don't understand your question. Are you asking if it would still be too many people in the "People" tab if it shows all people affiliated with all my movies?
Because that was not my issue. My issue was merely that I don't want to see people not connected to any media in my library.
For me the most interesting thing about the people tab is seeing what studios/actors/directors I have watched the most (sorting by item number).

**Comment by LnLcFlx** [comment]
I also have the same problem of too many entries with the "Genres" tab,
I have some 21k genres.

**Comment by IgnisDa** [comment]
I don't think I'll do this for genres, but I will keep this in mind.
