### ISSUE TITLE
[FEATURE REQUEST] - Tracking actors and directors upcoming projects

### ISSUE THREAD

**Issue by IO-B** [IgnisDa/ryot#708]
I am not sure if this is already a feature and i just cant find it.
I do use the "monitor a person" feature. But it would be great to have an option to also see upcoming projects. Maybe even show those in the calendar. 
Also i really like the way "letterboxd" visualizes projects a director or actor worked on. 
A nice little feature is their percentage/number of watched projects per actor/director.

![grafik](https://github.com/IgnisDa/ryot/assets/83821430/e033bcd4-f74a-4600-876f-a5ce32db6cf3)

**Comment by IgnisDa** [comment]
@IO-B On a different note, did you try importing data from letterboxd?

**Comment by IO-B** [comment]
no, i have not. I was just looking through different tools.

**Comment by saschabrockel** [comment]
Not sure if I should open a new issue but I would wish something similar. Some days ago I got this notification:

> Jackie Chan has been associated with Police Story 2 as Theme Song Performance
> Jackie Chan has been associated with Police Story 3: Super Cop as Presenter

That is information I don't really need as the movies are from the 90s and of course Jackie Chan is included but it seems that somebody added some info to TVDB or IMDB and triggered this if I understand it correctly.

It would be nice to have the option to only watch for upcoming projects or at least of the same year and older. It makes no sense for such old movies.

**Comment by IgnisDa** [comment]
I decided not to implement this feature.

This is because Ryot downloads as less data as possible for media items. This is primarily to save disk space. So for media associated to people, Ryot stores only minimal details: name and image. Thus, it does not have enough details to determine if a media items is "upcoming".

Working on this did allow me to rewrite the people details implementation so it will be much more accurate and have correct details. Thanks for opening the issue!
