### ISSUE TITLE
[FEATURE REQUEST] Native titles for animes (from anilist)

### ISSUE THREAD

**Issue by lo48576** [IgnisDa/ryot#866]
Similar to #475, but can the name in the native language (of the work) be used?
At first I guessed `ANIME_AND_MANGA_ANILIST_PREFER_ENGLISH=false` is it, but it uses Romaji title, not the native title.

**Comment by IgnisDa** [comment]
I think it would be better to use the `native` as default. Earlier it used `userPreferred` from the schema.

No need to introduce a new config parameter for this.

**Comment by mufeedali** [comment]
Hi @IgnisDa ,

Is it possible to use Romaji titles after this change?

**Comment by IgnisDa** [comment]
Isn't that the default behaviour?

**Comment by mufeedali** [comment]
![image](https://github.com/user-attachments/assets/ca786164-32f6-433e-94f5-8b42d7bd72f9)

This is how it is for me with the default configuration

**Comment by IgnisDa** [comment]
That looks fine to me, isn't that what you want?

**Comment by mufeedali** [comment]
Anilist has three options for anime and manga names: Native (which seems to be the current one), English (which also seems available as an option in Ryot) and Romaji.

Romaji is English transliteration of Japanese text. So in the above case, it should return the full transliterated title of "Mushoku Tensei: Isekai Ittara Honki Dasu", or "Shingeki no Kyojin" if it were "Attack on Titan".

Looking at the issue description, Ryot used to use Romaji but the fix for this issue made it so that only Native and English are now available.

**Comment by IgnisDa** [comment]
@mufeedali created new tracking issue.

**Comment by IgnisDa** [comment]
Can be set using `ANIME_AND_MANGA_ANILIST_PREFERRED_LANGUAGE=romaji`. Allowed values are `native`, `english`, `romaji`.

The old env variable: `ANIME_AND_MANGA_ANILIST_PREFER_ENGLISH` has been deprecated.
