### ISSUE TITLE
[FEATURE REQUEST] Rethink monitored media and updating them

### ISSUE THREAD

**Issue by Artnal** [IgnisDa/ryot#929]
Hi there, 

Was there an update to the categories recently? Almost all of my shows lost the tag "monitoring" without action on my part, which means the "upcoming" section is now basically empty. Did something change in teh way the categories work? I redid it manually, but I just wanted to check that it was intended behaviour.

Thanks!

Edit: after putting them back on the "Monitoring" list manually and running a "Perform all background tasks", the upcoming section is still empty. I'm not sure if I missed something, is that section now reserved to "Watchlist" category instead of "Monitoring"?

**Comment by IgnisDa** [comment]
Yes items are automatically removed from monitoring after 30 days.

> upcoming section is still empty

I think they should show up after the nightly cron job. If they do not, please ping me here.

**Comment by IgnisDa** [comment]
There is an env variable: `MEDIA_MONITORING_REMOVE_AFTER_DAYS` (defaults to 30) which can be used to control this.

But you raise a valid concern which I do not have a solution for. The reason I implemented this feature was because once too many movies/shows are added to the collection, the nightly cron job sends too many requests to tmdb and gets rate limited. I fear that the keys hard-coded into ryot might be banned.

Can you think of a better approach to this?

**Comment by IgnisDa** [comment]
I once implemented a solution using [collection templates](https://ryot.io/features/#supercharged_collections) which asked users how many days they want to keep media in monitoring. But the resulting UX was bad I removed it.

Maybe some kind of exponential back-off will work here? But I have never implemented those.

**Comment by IgnisDa** [comment]
> Is the calendar currently working on the same system as the "monitoring"?

As soon as a media is first committed to database, all the events associated to it are added to calendar. When a change is detected in a media, it is refreshed and new dates are also committed to the calendar and also clean up out dated ones.

> sonarr has probably figured out a way around this

Maybe you can get a PR going? :P

**Comment by IgnisDa** [comment]
> But those changes come from the same pulls as the ones for the "monitoring" category, or is it a separate one? (I'm wondering if it's possible to rely on the calendar to then trigger whether or not tvdb should be queried, or if it's just circular reasoning).

No the calendar committed to the db is not a reliable source for this purpose. The only reliable one is the TMDB API.

I think your idea of "cold storage" is pretty good. I will see what I can do.

**Comment by IgnisDa** [comment]
One problem I am encountering: there is no easy way to tell if a media item has actually changed. So I can't even track the `last_changed` field reliably. 🤔 idk how to solve this lol. Will have to give it more thought.

**Comment by elvis0288** [comment]
hey guys what about using status of the show, so for instance in tmdb there is a status field
![image](https://github.com/user-attachments/assets/4dd46f88-2a2b-4fdf-8e55-6cb5f870e2f6)

if that status field is 'ended' or 'canceled' as the example above, there after completing all episodes, it can be removed from monitoring because it is done (also the 30 days will work).

![image](https://github.com/user-attachments/assets/c17cd6ab-ab5b-4b1f-9b52-1e6e996bbaa1)
but is the status is other than 'ended' or 'canceled' they should continue to be monitoring even after completing all the episoded.. i do not think people will have more than 10 to 20 shows that they will be watching/waiting for a new season.

**Comment by IgnisDa** [comment]
That's a neat idea. What about media which is not from tmdb? For example books from open library. On what basis would they be removed?

**Comment by elvis0288** [comment]
well this will work for tv shows, for books i guess it should not matter as each book has its own name so i am not sure how you keep those but they are each its own. on tv shows you have the returning every year or 2 so that is what it makes it special and different

**Comment by IgnisDa** [comment]
So it would have to be monitored for 2 years 😱😱😱??

**Comment by elvis0288** [comment]
lol, well i mean i guess you can add a validation that if monitoring and not cancel or ended, can be check every month or so until you actually get the returning date for the first episode of the new season.. then it will get back to the normal monitoring.. i guess it needs a new parameter that will handle if the user finished it and it is not ended or cancelled then that parameter is set to true and it will trigger the API only once a month or so until it gets back the returning date, then it will go back into the regular monitoring. and it would also go into the up next to watch

**Comment by IgnisDa** [comment]
Closing this since I feel like this behaviour is fine.

**Comment by IgnisDa** [comment]
I have found a partial solution that will allow most shows to start working correctly. For my own reference:

> if an entity has updates, remove it from all Monitored collections and add them back again. If len(mediaStateChanges) > 0, then we know that the entity has updates so we can do the above
