### ISSUE TITLE
Mark as read: Randomizer

### ISSUE THREAD

**Issue by mobedoor** [IgnisDa/ryot#993]
While i do not recall exact dates that I consumed each media in the past, I can usually narrow them down to within an year. 
If it is a hard requirment for ryot to have it specified down to the day. I would like to request a quick don't remember button, that would randomly fill it with data.

**Comment by aureateflux** [comment]
There's already an option for "I don't remember" in the manual progress update modal, but I think this might be a reasonable option to have for when the user is marking a number of episodes as watched by clicking "mark all unseen episodes before this one as seen."

Currently, the behavior of that is for all those episodes to inherit the date you specify when selecting either "just now" or "custom date." With the upcoming focus on graphs and statistics, this could lead to inaccurate representations of how you're consuming a particular piece of media, where it looks like you've been bingeing when maybe you just... forgot to update it in Ryot. 

Maybe the default option could be to evenly space the watch events between the watch date of the last episode marked as watched and the one you're presently marking as watched, then have another option for "I binged this" to put them all on the same date (per current behavior). If someone wants the data more accurate than that, they will probably be setting each episode's watch date individually.

**Comment by IgnisDa** [comment]
I like the idea of spacing entries out though the randomizer won't be a good idea since that assumes input from the user that isn't there.

**Comment by mobedoor** [comment]
> There's already an option for "I don't remember" in the manual progress update modal, but I think this might be a reasonable option to have for when the user is marking a number of episodes as watched by clicking "mark all unseen episodes before this one as seen."

The weakness of I don't remember is that it wont reflect in graphs (I think) and as such is not really meaningful data for me.

> I like the idea of spacing entries out though the randomizer won't be a good idea since that assumes input from the user that isn't there.

I only suggested the randomizer as I didn't know the hard requirements for storage. I'm assuming it must be an exact date rather than month or year. And so the user could choose the correct year and click I don't remember on the month and date, and Ryot could assign a random date/month IF that was a requirement.
The spacing entries out would also be nice to have, where if the user simply selects a date range, the episodes are spaced out between them.

**Comment by IgnisDa** [comment]
> The weakness of I don't remember is that it wont reflect in graphs

It will be reflected. The graphs use the `finished_on` attribute and if that does not exist, then the `last_updated_on` (which always does).

>  And so the user could choose the correct year and click I don't remember on the month and date, and Ryot could assign a random date/month IF that was a requirement.

This is also a nice idea though Ryot will not be able to support it with the current schema.

**Comment by aureateflux** [comment]
I would argue that randomizing a date over such a large range would just reduce the quality of the data to the point of being nearly meaningless. 

If the user doesn't remember exactly when they consumed something, they can usually narrow it down better than "any random date across that whole year" (I'm pretty sure I read that in the fall, so I'll just say I finished it on November 15 of that year). Obviously this is higher quality than a randomly picked date, but even if the user has to pick a random date of their own, I would argue that inherently improves the quality of that data because 1) the user has control over the pick and 2) the user knows a random date has picked.

Maybe a middle ground could be an option in the modal asking the user if they want to specify a range in which to select a random date.

**Comment by IgnisDa** [comment]
I agree with @aureateflux. Though I don't think adding UI to "specify a range" will be prudent since it will just make the UI more complicated needlessly.

**Comment by mobedoor** [comment]
> It will be reflected. The graphs use the finished_on attribute and if that does not exist, then the last_updated_on (which always does).

I see, while reflected it's still not very representative as compared to a rough year.

> If the user doesn't remember exactly when they consumed something, they can usually narrow it down better than "any random date across that whole year" (I'm pretty sure I read that in the fall, so I'll just say I finished it on November 15 of that year). This is probably best done manually by the user and already supported by the current implementation; obviously this is higher quality than a randomly picked date. Even if the user has to pick a random date of their own, I would argue that inherently improves the quality of that data because 1) the user has control over the pick and 2) the user knows a random date has been picked.

In your specific example, I agree that manual entry would be superior for up to a month. Beyond that, it becomes a matter of diminishing returns. Personally, if I don't know the exact month, I would prefer not to be forced to choose specific months and dates, and I think most people would deem it unnecessary effort and would be annoyed by it.

**Comment by IgnisDa** [comment]
I personally believe the UI is fine this way since this is how Trakt allows users to update progress too. I think I will stick to this until I come across a suggestion that will make things radically more intuitive.

As for your case, if you don't know the exact day of the month, you can just select the 15th of it. It should show up in the "Last 365 days" graph that way for that month.

Closing for now.
